services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: comandei
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cmdi-api:
    build: ./api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/comandei
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  cmdi-web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - cmdi-api

volumes:
  db_data:
