spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/comandei}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.default-password=${APP_SEED_DEFAULT_PASSWORD:}

jwt.secret=${APP_JWT_SECRET}
jwt.expirationMs=${APP_JWT_EXPIRATION_MS:3600000}
